# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fd0cec09f8c5fb7c0c85afe34412b9abee67a15d59f01a157d16ae1687c9c704342ef78c51c3d7ec6d29e9b9c00562ad625aa5c4c62759f73d37b64a1ea5026

test:
  secret_key_base: 5230be15e2b5031503cb0297e10bf1c565a34d7a7a89e6ca04da8a0766c647d4d2cd2bafc516c0c2d84bac4961004b5783e767e5c81a511f26cb6dc940b750e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
